# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: read vacation 

on:
  # push:
    # branches: [ master ]
  schedule:
    - cron:  '20 11 * * *' # 오전 11시 20분에 실행.


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: do check and notify
      env:
        SESSION_ID_FOR_HIWORKS_NOTI: ${{ secrets.SESSION_ID_FOR_HIWORKS_NOTI }}
        TELEGRAM_BOT_TOKEN_FOR_HIWORKS_NOTI: ${{ secrets.TELEGRAM_BOT_TOKEN_FOR_HIWORKS_NOTI }}
        TELEGRAM_ID_OF_ADMIN_FOR_HIWORKS_NOTI: ${{ secrets.TELEGRAM_ID_OF_ADMIN_FOR_HIWORKS_NOTI }}
        VACATION_URL_FOR_HIWORKS_NOTI: ${{ secrets.VACATION_URL_FOR_HIWORKS_NOTI }}
      run: |
        # 실행해보자 
        python ./getVacation.py
